version: "3"
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: $PG_PASS
            POSTGRES_DB: $PG_DB
            POSTGRES_USER: $PG_USER
        ports:
            - $PG_OUTSIDE_PORT:5432
        volumes:
            - $PG_DATA_LOCATION:/var/lib/postgresql/data
    main:
        image: registry.atlantishq.de/ths/atlantis-contract-main
        restart: always
        depends_on:
            - postgres
        ports:
            - 5100:5000
        volumes:
            - $CONFIG_FILE:/app/config.py
            - $PROJECT_ROOT_DIR:/app/proj/
            - $TEMPLATES_DIR:/app/document-templates/
            - $BWA_FILE:/app/BWA.xls
    watcher:
        image: registry.atlantishq.de/ths/atlantis-contract-watcher
        restart: always
        depends_on:
            - postgres
        volumes:
            - $CONFIG_FILE:/app/config.py
            - $PROJECT_ROOT_DIR:/app/proj/
    importer:
        image: registry.atlantishq.de/ths/atlantis-contract-importer
        depends_on:
            - postgres
        volumes:
            - $CONFIG_FILE:/app/config.py
            - $PROJECT_ROOT_DIR:/app/proj/
    monitoring:
        image: registry.atlantishq.de/ths/atlantis-contract-monitoring
        restart: always
        depends_on:
            - postgres
            - main
        volumes:
            - $CONFIG_FILE:/app/config.py
