name: ci

on:
  push:
    branches:
      - "master"
      - "feature/mounted-fs-backend"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
        name: prod
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            main:
              - 'docker/docker-main/**'
            watcher:
              - 'docker/docker-watcher/**'
            importer:
              - 'docker/docker-importer/**'
            monitoring:
              - 'docker/docker-monitoring/**'
      -
        name: Checkout
        if: steps.filter.outputs.main == 'true' || steps.filter.outputs.watcher == 'true' || steps.filter.outputs.importer == 'true' || steps.filter.outputs.monitoring == 'true'
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        if: steps.filter.outputs.main == 'true' || steps.filter.outputs.watcher == 'true' || steps.filter.outputs.importer == 'true' || steps.filter.outputs.monitoring == 'true'
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        if: steps.filter.outputs.main == 'true' || steps.filter.outputs.watcher == 'true' || steps.filter.outputs.importer == 'true' || steps.filter.outputs.monitoring == 'true'
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Registry
        if: steps.filter.outputs.main == 'true' || steps.filter.outputs.watcher == 'true' || steps.filter.outputs.importer == 'true' || steps.filter.outputs.monitoring == 'true'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: Contract-Main
        if: steps.filter.outputs.main == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./docker/docker-main/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/ths/atlantis-contract-main:latest"
      -
        name: Contract-Watcher
        if: steps.filter.outputs.watcher == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./docker/docker-watcher/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/ths/atlantis-contract-watcher:latest"
      -
        name: Contract-Importer
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.importer == 'true'
        with:
          context: ./docker/docker-importer/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/ths/atlantis-contract-importer:latest"

      -
        name: Contract-Importer
        uses: docker/build-push-action@v3
        if: steps.filter.outputs.monitoring == 'true'
        with:
          context: ./docker/docker-monitoring/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/ths/atlantis-contract-monitoring:latest"
